Organize workflow
mangoszero/server pull request #185
Opened 2023-02-10 14:48 UTC by Pysis868

How palatable are these changes, if even relevant now?

2023-07-25 10:26 UTC, billy1arm commented
@Meltie2013 Does this look ok to you ?

2024-08-01 13:44 UTC, Meltie2013 commented on apps/ci/ci-compile.sh
> -# Check for & make directories
This should remain to see if the directory exists already or not.

2024-08-01 13:50 UTC, Meltie2013 commented
@billy1arm Once I see an updated workflow with the changes in play, will make the call.

2024-08-18 20:21 UTC, billy1arm commented on src/modules/Eluna
@Pysis868 can you revise this to the latest revision

2024-08-18 20:21 UTC, billy1arm commented on src/realmd
@Pysis868 can you revise this to the latest revision

2024-08-18 20:21 UTC, billy1arm commented on src/tools/Extractor_projects
@Pysis868 can you revise this to the latest revision

2024-08-18 20:22 UTC, billy1arm commented on dep
@Pysis868 can you revise this to the latest revision

2024-08-18 20:23 UTC, billy1arm requested changes
@Pysis868 can you revise this to the latest revision for the submodules ?

2024-08-28 19:29 UTC, Pysis868 commented
As of a270f226afbfaff6e4158c7b1725b7c7d798eca5, and an extra `win` `master` ref and pull, which provided no additional changes after committing:

```
> git submodule
 c02243ee29630c0d3b51f69d49589332927c9c0e dep (heads/master)
 5ca638f99fcd4a9f2cc94b42d0443ffa010618d0 src/modules/Eluna (heads/master)
 519bbc302878681abf25685a4f0e7df5db560bc9 src/modules/SD3 (heads/master)
 e63d3a3bd9f36497909e8e040a00055f205e7063 src/realmd (heads/master)
 1d533d5fec24fce8237e81d863f8270330363303 src/tools/Extractor_projects (heads/master)
 8c5fdae01893ad16af975a3eeee02585692452ac win (heads/master)
```

2024-08-28 22:01 UTC, Pysis868 commented
```
git submodule status
 c02243ee29630c0d3b51f69d49589332927c9c0e dep (heads/master)
 058ffa1cb7f81bb111e3022d572a6311558c1d5f src/modules/Eluna (058ffa1)
 443cd7a5f701066cff624e3201f45de645f49cd2 src/modules/SD3 (heads/master-6-g443cd7a)
 e63d3a3bd9f36497909e8e040a00055f205e7063 src/realmd (heads/master)
 1d533d5fec24fce8237e81d863f8270330363303 src/tools/Extractor_projects (heads/master)
 8c5fdae01893ad16af975a3eeee02585692452ac win (heads/master)

```

2024-08-29 08:48 UTC, billy1arm commented on apps/ci/ci-compile.sh
@Pysis868 I sent you some more detailed questions about this file on discord

2024-08-29 14:54 UTC, Pysis868 commented on apps/ci/ci-compile.sh
Sounds like your handling it.
Need anything else, let me know.

2024-08-29 15:54 UTC, Pysis868 commented
```
Run ./apps/ci/ci-packages.sh
  ./apps/ci/ci-packages.sh
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/870baad1-32d8-40b1-9a44-fa551d09bc65.sh: line 1: ./apps/ci/ci-packages.sh: Permission denied
Error: Process completed with exit code 126.
```
`apps/ci/ci-compiler-update.sh` uses sudo, so thought it would be fine for this package script too.  The workflow simply runs the scripts, and thought it was working before as well, since there was a build folder fix added.

2024-08-30 03:11 UTC, Meltie2013 commented on .github/workflows/core_build.yml
> +        run: ./apps/ci/ci-packages.sh
This should be:
`run: source ./apps/ci/ci-packages.sh`

2024-08-30 03:11 UTC, Meltie2013 requested changes
@Pysis868 Please check comment for details.

2024-08-30 03:16 UTC, Meltie2013 commented on .github/workflows/core_windows_build.yml
> +        run: apps/ci/ci-submodule-update.sh
This line should be reverted back to how it was, since Shell files can not run in Windows.

2024-08-30 17:01 UTC, Pysis868 reviewed
> Reviewed 2 of 4 files at r1, 1 of 6 files at r2, 1 of 1 files at r3, 3 of 4 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mangoszero/server/185)* status: all files reviewed, 8 unresolved discussions (waiting on @billy1arm and @Meltie2013)

___
*[`.github/workflows/core_build.yml` line 21 at r6](https://reviewable.io/reviews/mangoszero/server/185#gh-1737786040:-O5WbgxnAKlnMDwtcMDo:b-896fix) ([raw file](https://github.com/mangoszero/server/blob/06d12e26613d9e29ff4fce9c09794490b60dc810/.github/workflows/core_build.yml#L21)):*
<details><summary><i>Previously, Meltie2013 wrote…</i></summary><blockquote>

This should be:
`run: source ./apps/ci/ci-packages.sh`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-30 17:03 UTC, Pysis868 reviewed
> *[Reviewable](https://reviewable.io/reviews/mangoszero/server/185)* status: all files reviewed, 8 unresolved discussions (waiting on @billy1arm and @Meltie2013)

___
*[`apps/ci/ci-compile.sh` line 0 at r2](https://reviewable.io/reviews/mangoszero/server/185#gh-1700204911:-O5ZEQi9-Op_XzXLyfoX:b-896fix) ([raw file](https://github.com/mangoszero/server/blob/ff8a942ebe2e0ca779729a0f8a9eaf5bf4697332/apps/ci/ci-compile.sh#L0)):*
<details><summary><i>Previously, Meltie2013 wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/mangoszero/server/pull/185#discussion_r1700204911) to the right spot — sorry!)*

This should remain to see if the directory exists already or not.
</blockquote></details>

Done.
___
*[`src/realmd` line 0 at r4](https://reviewable.io/reviews/mangoszero/server/185#gh-1721049974:-O5ZERqR4-Evm_rp-RCe:b-896fix) ([raw file](https://github.com/mangoszero/server/blob/5980cb23a1371b1b20cab4258bdec19615269df0/src/realmd#L0)):*
<details><summary><i>Previously, billy1arm (Antz) wrote…</i></summary><blockquote>

@Pysis868 can you revise this to the latest revision
</blockquote></details>

Done.
___
*[`dep` line 0 at r4](https://reviewable.io/reviews/mangoszero/server/185#gh-1721050093:-O5ZETFK3KtqiqR8Cqe8:b-896fix) ([raw file](https://github.com/mangoszero/server/blob/5980cb23a1371b1b20cab4258bdec19615269df0/dep#L0)):*
<details><summary><i>Previously, billy1arm (Antz) wrote…</i></summary><blockquote>

@Pysis868 can you revise this to the latest revision
</blockquote></details>

Done.
___
*[`.github/workflows/core_windows_build.yml` line 29 at r6](https://reviewable.io/reviews/mangoszero/server/185#gh-1737810080:-O5ZEUGW7lG49M7jM0OZ:b-896fix) ([raw file](https://github.com/mangoszero/server/blob/06d12e26613d9e29ff4fce9c09794490b60dc810/.github/workflows/core_windows_build.yml#L29)):*
<details><summary><i>Previously, Meltie2013 wrote…</i></summary><blockquote>

This line should be reverted back to how it was, since Shell files can not run in Windows directly.
</blockquote></details>

Done.
___
*[`src/modules/Eluna` line 0 at r4](https://reviewable.io/reviews/mangoszero/server/185#gh-1721049955:-O5ZEUoe42KrvrsWymwJ:b-896fix) ([raw file](https://github.com/mangoszero/server/blob/5980cb23a1371b1b20cab4258bdec19615269df0/src/modules/Eluna#L0)):*
<details><summary><i>Previously, billy1arm (Antz) wrote…</i></summary><blockquote>

@Pysis868 can you revise this to the latest revision
</blockquote></details>

Done.
___
*[`src/tools/Extractor_projects` line 0 at r4](https://reviewable.io/reviews/mangoszero/server/185#gh-1721050017:-O5ZEVHW6PSRBDi3z58c:b-896fix) ([raw file](https://github.com/mangoszero/server/blob/5980cb23a1371b1b20cab4258bdec19615269df0/src/tools/Extractor_projects#L0)):*
<details><summary><i>Previously, billy1arm (Antz) wrote…</i></summary><blockquote>

@Pysis868 can you revise this to the latest revision
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-01 18:18 UTC, Meltie2013 approved these changes

2024-09-20 17:49 UTC, Pysis868 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mangoszero/server/185#-:-O7FYAzSEi1AdnX2oRhl:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @billy1arm and @Meltie2013)



<!-- Sent from Reviewable.io -->

2024-09-20 17:50 UTC, Pysis868 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mangoszero/server/185#-:-O7FYSgfDcEgmLEotjTJ:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @billy1arm and @Meltie2013)



<!-- Sent from Reviewable.io -->

2024-10-01 08:23 UTC, billy1arm reviewed
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, 3 of 4 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mangoszero/server/185)* status: all files reviewed, 8 unresolved discussions (waiting on @Meltie2013)



<!-- Sent from Reviewable.io -->

2024-10-01 08:23 UTC, billy1arm approved these changes

2026-03-05 00:12 UTC, closed without merging